services:

    sg_datatables.serializer.method:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer

    sg_datatables.serializer.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder

    sg_datatables.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            - [@sg_datatables.serializer.method]
            - [@sg_datatables.serializer.encoder.json]

    sg_datatables.column.builder:
        class: Sg\DatatablesBundle\Column\ColumnBuilder

    sg_datatables.datatable.view.factory:
        class: Sg\DatatablesBundle\Datatable\View\DatatableViewFactory
        arguments: [@templating, @translator, @router, %sg_datatables.default.layout.options%, @sg_datatables.column.builder]

    sg_datatables.twig.extension:
        class: Sg\DatatablesBundle\Twig\DatatableTwigExtension
        tags:
            - { name: twig.extension }

    sg_datatables.datatable:
        class: Sg\DatatablesBundle\Manager\DatatableDataManager
        scope: request
        arguments: [@doctrine, @request, @sg_datatables.serializer]
